title: MyEmbroids
email: info@myembroids.com
description: >
  MyEmbroids is the simplest way to organize your designs,
  without having to spend hours!
url: "https://blog.myembroids.com"
facebook_username: MyEmbroids
twitter_username: MyEmbroids
landing_url: "https://www.myembroids.com"

markdown: kramdown
